### ISSUE TITLE
add bindings for the other functions of libdivsufsort

### ISSUE THREAD

**Issue by louisabraham** [louisabraham/pydivsufsort#11]

**Comment by seanlaw** [comment]
This is well beyond what I am using this package for so I trust your judgement. If you want to point me to some relevant reading material then I can brush up and maybe provide some input?

**Comment by louisabraham** [comment]
> If you want to point me to some relevant reading material then I can brush up and maybe provide some input?

I'm not sure I lack information at this point, but thanks for proposing :)

The need for a class to handle `sa_search` is also motivated by #24: it would be much nicer to have something like

```python
s = "blablablabla"
index = Index(s)

index.search("abla")

index.lcp(0, 3)
```

**Comment by seanlaw** [comment]
Okay, I am on board with that. I think you’ve sufficiently motivated the need for a class (but I’m sure you’ve already justified to yourself 😊).

I’m sure it’s just an example but I’d request for a better class name than “Index”. Something more obvious or descriptive. Otherwise, one would/could reuse the package name as the class name if it were simpler or more compact. But, again, good/clear/illustrative docstrings and examples would demonstrate the full range of how to use it.

**Comment by louisabraham** [comment]
I just raise an error when an input other than bytes is given to the other functions. All functions are unit tested using reference implementations in Python.
