### ISSUE TITLE
Querying Sequences With Insertions, Deletions, and Mutations

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#27]
Let's say I have a million sequences that are between 10-1000 steps in length. First, I append a unique "sentinel step" to the end of each sequence and then I concatenate all of them together and compute the `suffix_array` and `lcp_array` with this concatenated (superset) sequence. From the `lcp_array` I can identify the subsequence, `A`, with the highest frequency counts but I am also curious to identify other subsequences that are "close" to `A`. 

In this case, "closeness" may be measured by one or more of the following:

1. Insertion of one or more steps (in neighboring or scattered locations)
2. Deletion of one or more steps (in neighboring or scattered locations)
3. Mutation/change of one or more steps (in neighboring or scattered locations)

Where a user may "punish", say, a mutation as being 2x farther away than, say, a deletion and only half as far away as a single step insertion (all hypothetical). Again, the user can decide how many insertions, deletions, and mutations are allowable via a user defined function or user defined weights. So, while the `lcp_array` gives us exact matches, it would be nice to be able to find these near matches with, say, 20%-30% "difference" in sequence.

@louisabraham Any ideas on how one might be able to achieve this efficiently? I think that this would be a tool that people would use. It's essentially a form of "fuzzy sequence matching" like one might find in DNA sequences except that I have 1,000-10,000+ different nucleotides (instead of only 4)

**Comment by louisabraham** [comment]
You are describing the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).

I think the problem you are describing can reasonably not be computed exactly in reasonable time.

A fast implementation of the Levenshtein distance and related metrics could be an idea for this library but I think that approximating queries at that scale is a hard problem that is not in the scope of a library for suffix arrays.

An area to look at is locality sensitive hashing with algorithms like SimHash, MinHash or even this recent paper: https://academic.oup.com/bioinformatics/article/35/14/i127/5529166

You could also use the technique from https://bergvca.github.io/2017/10/14/super-fast-string-matching.html

On the other hand, because you have so many nucleotides, you could first build a mapping that indicated the positions at which a nucleotide appears and compute the Levenshtein distances from that point.

With 1k nucleotides and 1M texts of length 1000, the probability that 3 nucleotides appear in a text is only 10^-6 so they appear in very few texts if they are random. I guess that the idea of the blog post is adapted to your problem.

**Comment by seanlaw** [comment]
Thanks for talking through it. It certainly sounds like LSH or the string matching approach would be useful.

Originally, I was thinking about approaching the problem with some sort of fuzzy string matching

**Comment by louisabraham** [comment]
Now I'm not sure I understand what you want to do. I thought you wanted to find a substring that "almost" appears at a lot of places. This is hard because most approaches would be in O(n**2) with n being 1M of strings.

Also, to find A in your first post, I'm pretty sure you need to choose a length first.

I don't really understand how you want to use fuzzy string search.

Maybe you should just modify the levenshtein distance to make it non symetrical and allow adding characters at the end

**Comment by louisabraham** [comment]
Oops, my finger slipped.

**Comment by seanlaw** [comment]
No, I don't know of any implementation. I'll have to put some more thought into it and establish a real example.

**Comment by louisabraham** [comment]
A random thought: you probably want to detect patterns that approximately appear a lot of times. Maybe the most frequent substring `A` of length `k`  is not the "center" of those patterns that appear a lot of times in terms of edit distance, nor even related. You could imagine that the second most frequent substring, when accounting for the approximate matches, is the one you want.

What you could do is instead take the `m` most frequent substrings in `O(n log m)` given the LCP array (and ignore the substrings with with separators) and compute the `m^2` levenshtein distances in `O(m^2 k^2)`. Then you apply some clustering algorithm. In metric clustering there is the ability to average points to produce representatives, but CLINK and SLINK hierarchical clusterings don't use it and can run in `O(m^2)`. I'm pretty sure the sklearn implementation works efficiently.

You can then easily *cut* the dendrogram at some levels corresponding to 20% or 30% of k as you wanted.

In the above steps, this repository could provide the counting and ranking of substrings of length `k` and the Levenshtein distance computation.

Maybe there is a clever way to speed up the computation of all-pairs Levenshtein distances but I don't know it.

See also these two related stackexchange answers: https://cs.stackexchange.com/q/27539/42569 https://cs.stackexchange.com/q/53299/42569

**Comment by louisabraham** [comment]
What do you think about this @seanlaw? Is the above solution suitable for your needs?

**Comment by seanlaw** [comment]
Yes, I think that is good enough for now. I’ll re-open if it isn’t. Thanks for your help!

**Comment by louisabraham** [comment]
> In the above steps, this repository could provide the counting and ranking of substrings of length k and the Levenshtein distance computation.

You are welcome to add them to the repository / I can implement them as well.

**Comment by seanlaw** [comment]
It’ll be a while before I have bandwidth so feel free to tackle it but don’t feel pressured to

**Comment by louisabraham** [comment]
Pushed in the latest version :)

See https://github.com/louisabraham/pydivsufsort/blob/master/examples/most_frequent_substrings.py for an example or https://github.com/louisabraham/pydivsufsort/blob/master/pydivsufsort/stringalg.pyx#L215-L241 for the docstring

It produces outputs like

```
'ing' appeared 7 times
'the' appeared 6 times
'ng ' appeared 6 times
'he ' appeared 6 times
' th' appeared 6 times
'rem' appeared 5 times
'ore' appeared 5 times
' in' appeared 5 times
```

As a side note, it was quite interesting to code because I had to use C++ types.
